apiVersion: v1
kind: Service
metadata:
  name: voyage-analytics-service
  namespace: voyage-analytics
spec:
  selector:
    app: voyage-analytics
  type: NodePort   # For local testing
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 30050   # Access via localhost:30050